### ISSUE TITLE
ModuleBuildError : 'SassError: Undefined function.'

### ISSUE THREAD

**Issue by botaditya** [Brakebein/ngx-tagify#11]
Getting the following error while compilation. I added scss to my angular.json and done all the necessary imports and configurations.

`Error: ./node_modules/ngx-tagify/styles/tagify.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined function.
    ╷
267 │                     $size: math.div(-$tagMargin, 2);
    │                            ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\@yaireo\tagify\src\tagify.scss 267:28  @import
  node_modules\ngx-tagify\styles\tagify.scss 1:9      root stylesheet`

[IMAGE]
![image](https://user-images.githubusercontent.com/46053408/144361180-2a990f5d-779b-4735-ae06-b7605980f1b9.png)

**Comment by Brakebein** [comment]
The `math.div` sass function is defined in the scss of the core library [@yaireo/tagify/src/tagify.scss L267](https://github.com/yairEO/tagify/blob/39a9ed69a8b22635afe14948d655d1e71b5e100a/src/tagify.scss#L267). It seems like, you are running an older project. [`math.div`](https://sass-lang.com/documentation/modules/math#div) has been introduced in sass@1.33.0, which was released 6 months ago. Hence, updating your sass dependencies should resolve your issue (https://stackoverflow.com/questions/67857768/sass-math-div-function-is-undefined-in-angular-app-but-is-defined-in-angular-li). Upgrading Angular should also help.
