### ISSUE TITLE
I.m trying to remove all values from tagify using reactive form I reset all the form controls but the tagify tags are not deleted how can I delete them?

### ISSUE THREAD

**Issue by NorhanSamir** [Brakebein/ngx-tagify#12]

**Comment by Brakebein** [comment]
How are you trying to delete them? Can you share some code?

Please keep in mind that the component does not deep check for changes, and it also won't recognize changes in the array length. See README:

> __Note:__ The component only recognizes reference changes, it won't deep check for changes within the array. `this.tags.push({value: 'bar'});` won't do anything. Instead, use `this.tags = this.tags.concat([{value: 'bar'}]);` (or similar) to update changes.

To reset a reactive forms control value, just set an empty array:

```typescript
this.form.setValue({
  tags: []
});
```

**Comment by NorhanSamir** [comment]
Thank you it works fine.
this.form.setValue({
  tags: []
});
I was trying to reset it using reset control
This.formgroup.reset();
