### ISSUE TITLE
Users List Help

### ISSUE THREAD

**Issue by AbigailSlz** [Brakebein/ngx-tagify#28]
Hi!

Do you have any example of how to do this in angular?

Thanks!

![image](https://user-images.githubusercontent.com/56094826/182744093-460e4c0a-eb41-4392-b3fc-1da062676d20.png)

**Comment by Brakebein** [comment]
As this is just a wrapper for @yaireo/tagify, only the basic features are implemented in an Angular way.
So, you are not able to pass in any Angular templates for custom tag or dropdown rendering.
But you are still able to customize the tagify with all its settings as in the [users list example](https://yaireo.github.io/tagify/#users-list).
It's a little bit hacky, but possible.

I have added a new example to the [demo page](https://brakebein.github.io/ngx-tagify/) implementing the users list example from @yaireo/tagify. There you can also have a look at the code.

**Comment by AbigailSlz** [comment]
Thanks!!
