### ISSUE TITLE
Update Angular 14

### ISSUE THREAD

**Issue by jmtt89** [Brakebein/ngx-tagify#29]
Hi, can you update the peer dependencies for angular 14?

Currently when I try to do an `npm install` on angular 14 project I get this error

```
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.1.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.3.11" from ngx-tagify@0.7.2
npm ERR! node_modules/ngx-tagify
npm ERR!   ngx-tagify@"^0.7.2" from the root project 
```

**Comment by Brakebein** [comment]
Oh, my fault. When I updated the dependencies last time, the peer dependencies were overridden. I will fix it next week.

However, you should be able to use version 0.7.1.

**Comment by roymilder** [comment]
> Oh, my fault. When I updated the dependencies last time, the peer dependencies were overridden. I will fix it next week.
> 
> However, you should be able to use version 0.7.1.

I was literally _at the same moment_ experiencing this issue :). thanks for the suggestion
