### ISSUE TITLE
mode as 'mix' not working

### ISSUE THREAD

**Issue by rynangeles** [Brakebein/ngx-tagify#3]
{
mode: 'mix',
pattern: /@|#|~|%|&|-/
}

tags.find is not a function 

https://github.com/Brakebein/ngx-tagify/blob/b8e60313ae045eaa6e0c6e22e90f32008a991ede/projects/ngx-tagify/src/lib/tagify.component.ts#L96

**Comment by Brakebein** [comment]
Sorry, I have to admit that haven't really tested the mixed mode. I will fix it within the next days.

**Comment by Brakebein** [comment]
@rynangeles Can you please provide some more information and/or code snippets how you use it exactly? I can't reproduce your error.

I'm just adding support to load some initial mixed text & tags string.

**Comment by rynangeles** [comment]
I'm using the reactive form and my value is a string. so for example the value is 'the quick brown fox. {{{this_is_a_tag}}}' `{{{}}}` as my interpolator and the  **tags** which I guess is the value from a reactive form field. If **value/tags** is a string, then definitely ` String.find()` method will throw an error.

**Comment by Brakebein** [comment]
You may checkout the newest version. An initial string is now accepted with `ngModel` or reactive forms. But keep in mind that it gets parsed and transformed to tags. So, the initial string will be replaced by an array of tags.

Alternatively, you can pass a predefined value between the element tags: `<tagify>tag 1, tag 2</tagify>`. See readme and demo for details.

**Comment by rynangeles** [comment]
I think it would be better if the `mode : mix` preserve that string as its value.

**Comment by Brakebein** [comment]
You mean if the initial string value is `{{{this_is_a_tag}}} some text {{{tag}}}`, then you add `more text` and an `additional tag`, the string returned should be  `{{{this_is_a_tag}}} some text {{{tag}}} more text {{{additional tag}}}` ?

I thought of it as well, but I maybe overlooked some of docs:
https://github.com/yairEO/tagify#output-value
I also just looked deeper in the code and found this:
https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1480-L1539

So, it should be possible. I will go for it within the next days.

**Comment by Brakebein** [comment]
In the newest version, the output type now corresponds with the input type, i.e. either `string` or `TagData[]`.

However, for `mode: 'mix'`, if the input value is, e.g., `[[cartman]] and [[kyle]]`, the output string will be `[[{"value":"cartman"}]] and [[{"value:"kyle"}]]`. If you only want the pure value within the tag interpolators without the JSON syntax, you may need to address this issue to the [core library](https://github.com/yairEO/tagify). There should be some user-defined method similar to `originalInputValueFormat` to define the output format for tags and called within the `getMixedTagsAsString()` method.
https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1480-L1539
