### ISSUE TITLE
Property 'elm' does not exist on type 'DropDownSelectEventData<TagData>'.ts(2339)

### ISSUE THREAD

**Issue by sssrit** [Brakebein/ngx-tagify#30]
Hi,
I am getting the error in Property 'elm' does not exist on type 'DropDownSelectEventData<TagData>'.ts(2339) in dropdown:select property of callback. I am using tagify in angular. (Image attached)

![185594858-d75791f5-d21c-457f-a43c-25e71e0bef8a](https://user-images.githubusercontent.com/8317947/185790942-a361e852-9b42-4b8d-bd26-19dffd9dd27e.png)

I am following the same code suggested in https://github.com/Brakebein/ngx-tagify/blob/master/src/app/example-templates/example-templates.component.ts

Please Advice me to solve the error

**Comment by Brakebein** [comment]
The typings for @yaireo/tagify have changed recently ([see DT pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61578/files#diff-f34554b0e5892718034fb26575e773b005ba6b860f4b3f2af6e363d058778cfcR1126-R1130)).
Please make sure that your dependency for `@types/yaireo__tagify` is at least `4.15.1` or just update `ngx-tagify` to `0.7.3`.
