### ISSUE TITLE
Angular - ERROR ReferenceError: content is not defined on programmatically(on button click or drag drop event) adding mix tags.

### ISSUE THREAD

**Issue by tarungiri** [Brakebein/ngx-tagify#35]
I recently start facing "content is not defined" issue while I am adding Tag programmatically using "tagifyService.get("xyz").addMixTags([{ value: tagId, text: tagValue, title: tagValue, type: tagType }])".

![image](https://user-images.githubusercontent.com/39086277/202210051-dcfe3fc9-72fe-4e78-bbf6-bbab131ce3e0.png)

**Comment by Brakebein** [comment]
@yaireo/tagify recently published some new releases. After a quick investigation I could identify the section where he introduced this bug: https://github.com/yairEO/tagify/compare/v4.16.4...v4.17.2#diff-c25a58bcb38aa4fa6506c3017ab957bd356e6fc9f577cc256c8befe559b40050R664-R665 (expand the code snippet above to see that there is no `content` defined)

You may want to report this issue at [@yaireo/tagify](https://github.com/yairEO/tagify).

**Comment by Brakebein** [comment]
Ok, I just saw that you already reported this issue there (https://github.com/yairEO/tagify/issues/1148)

**Comment by yairEO** [comment]
SO maybe this isn't even related to Angular. Please verify by using the JSBIN template (which a link to is in the issue template) and set up the demo according to your needs
