### ISSUE TITLE
Can't Build when i use in Angular with "allowSyntheticDefaultImports": true

### ISSUE THREAD

**Issue by sohaibahsan007** [Brakebein/ngx-tagify#4]
when i try to build Angular 11, and when I run it, get this error. 

Uncaught ReferenceError: Cannot access 'qe' before initialization.

**Comment by Brakebein** [comment]
Is this a build or a runtime error?

According to the docs, `allowSyntheticDefaultImports` only affects type checking.

> This flag does not affect the JavaScript emitted by TypeScript, it only for the type checking.

https://www.typescriptlang.org/tsconfig/#allowSyntheticDefaultImports

I don't know what other libraries you are using, how you import them, and which part of your code is actually causing your error. Try setting `"esModuleInterop": true` in your tsconfig. Maybe this solves the problem.

https://www.typescriptlang.org/tsconfig/#esModuleInterop

**Comment by sohaibahsan007** [comment]
I had target es2015 in my app. when I change it back to es5 by looking at your example, it worked. but broke some other code.

**Comment by Brakebein** [comment]
In my other project using ngx-tagify, I have set `"target": "es2015"` (set by angular-cli during project initialization). I recently upgraded it from Angular 10 and 11, and I have no problems during build or runtime. For modern browsers, it shouldn't much matter which target is set. I think, it's more an issue with your other code (I don't know your code, so I can't really say much about it).

**Comment by sohaibahsan007** [comment]
i had fixed it, it was caused by a circular dependency.
