### ISSUE TITLE
Can not use the function "placeCaretAfterNode".

### ISSUE THREAD

**Issue by bgbglll** [Brakebein/ngx-tagify#47]
version:
"ngx-tagify": "0.7.6"

Can not call placeCaretAfterNode, below is my code snippet:
```
addTagsToForm() {
    let value = "My Tag";
    let tag: TagData = { value: value };
    let tagElement = this._tagifyService.get("MixedTagArea").createTagElem(tag);
    this._tagifyService.get("MixedTagArea").injectAtCaret(tagElement);
    let elementAfterTag = this._tagifyService
      .get("MixedTagArea")
      .insertAfterTag(tagElement, "");
    this._tagifyService
      .get("MixedTagArea")
      .placeCaretAfterNode(elementAfterTag);
  }
```
  
The reason not use addTags is that I used a button to trigger addTagsToForm() and I want to place caret after insert tags.

Please help.

**Comment by Brakebein** [comment]
You are basically using the core library `@yaireo/tagify`. With the latest release [v4.17.9](https://github.com/yairEO/tagify/releases/tag/v4.17.9), `placeCaretAfterNode()` moved to helpers file and is not exposed anymore (https://github.com/yairEO/tagify/commit/1d41a6980507de07d7161846125aea26a842aa7e). You should report there that this is a breaking change, and he should expose this function again. Or you can manually install `@yaireo/tagify@4.17.8` (which would however be just a workaround).

**Comment by bgbglll** [comment]
I see. Thank you so much!
