### ISSUE TITLE
trigger dropdown on whitelist update

### ISSUE THREAD

**Issue by Arnaves** [Brakebein/ngx-tagify#6]
I am updating the tags in white list based on pagination on a button click
how can i trigger the dropdown on white list change

**Comment by Brakebein** [comment]
I'm not sure what you exactly mean with "trigger". Do you want the dropdown list to be visible after you have clicked the button and updated the whitelist (even if the minimum number of characters has not yet be entered)?

**Comment by Brakebein** [comment]
To toggle the dropdown list, you need to call an internal method of the tagify instance. It's not at the official docs of @yaireo/tagify, but we included most of the internal methods in the type declarations (@types/yaireo__tagify).

You gain access to the full Tagify API via the `TagifyService` (also see [readme](https://github.com/Brakebein/ngx-tagify#service)). With the tagify instance, you can now call `tagify.dropdown.show.call(tagify);`.

```html
<tagify name="test"
        [settings]="settings"
        [whitelist]="whitelist$">
</tagify>

<button (click)="update()">Update</button>
```

```typescript
export class AppComponent {

  settings: TagifySettings = {
    // ...
  };

  whitelist$ = new BehaviorSubject<string[]>([]);

  constructor(
    private tagifyService: TagifyService
  ) { }

  update() {

    // update whitelist
    this.whitelist$.next(['some', 'new', 'tags']);

    // get tagify instance
    const tagify = this.tagifyService.get('test');
    // call internal method to unhide dropdown list
    tagify.dropdown.show.call(tagify);

  }

}
```

**Comment by Arnaves** [comment]
this.whitelist$.next(Array.from(new Set(this.arr)));
      this.spinner.show();
      setTimeout(() => {
        /** spinner ends after 5 seconds */
        this.spinner.hide();
      }, 1000);
      const tagify = this.tagifyService.get('tagscontest');

error:

Property 'get' does not exist on type 'TagifySettings<TagData>'

**Comment by Arnaves** [comment]
I am getting an error

**Comment by Brakebein** [comment]
Are you sure that you have injected `TagifyService` (and not `TagifySettings`)?

```typescript
constructor(
  private tagifyService: TagifyService
) { }
```

**Comment by Arnaves** [comment]
Thanks soo much Brakebein , have been fighting for this for soo many days now......you finally solved it

**Comment by Arnaves** [comment]
Brakebein can you guide me in updating the whitelist on scroll event of the suggestion window
