### ISSUE TITLE
IE11 - Not able to select the tag from dropdown.

### ISSUE THREAD

**Issue by LalitAgrawala004** [Brakebein/ngx-tagify#9]
Hi 

I am trying to use ngx-tagify in IE11 with whitelist. I am able to see my whitelist data in dropdown but on clicking on the item, nothing is happening.

I also included tagify.polyfills.min.js from @yaireo\tagify\dist but still it is not working. I can see
 ```
merge(
      fromEvent(this.tagify, 'add'),
      fromEvent(this.tagify, 'remove')
    )
``` 
not firing. 

can you please help me out here? Thanks a lot in advance.

**Comment by Brakebein** [comment]
Did you test the demos of the core library, https://yaireo.github.io/tagify/ ? If they are not working with IE11 as well, it might be an issue with the core library.

I will have a look at it next week (I'm currently on the road).

**Comment by LalitAgrawala004** [comment]
@Brakebein I did further investigation. it's issue on https://yaireo.github.io/tagify/. I created a PR with a fix. I am closing this issue. Thanks

**Comment by yairEO** [comment]
Hi, I've stopped supporting IE11, sorry, too much effort and some unsolvable issues as well
